FROM pactfoundation/pact-broker:latest

# Build arguments for configuration
ARG PACT_BROKER_EXTERNAL_URL
ARG PACT_BROKER_BASIC_AUTH_USERNAME
ARG PACT_BROKER_BASIC_AUTH_PASSWORD

# Set environment variables
ENV PACT_BROKER_DATABASE_URL=${PACT_BROKER_EXTERNAL_URL}
ENV PACT_BROKER_BASIC_AUTH_USERNAME=${PACT_BROKER_BASIC_AUTH_USERNAME}
ENV PACT_BROKER_BASIC_AUTH_PASSWORD=${PACT_BROKER_BASIC_AUTH_PASSWORD}

# Expose the port
EXPOSE 9292
