version: '3'
services:
  pact-broker:
    build:
      context: .
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_URL: ${PACT_BROKER_EXTERNAL_URL}
      PACT_BROKER_BASIC_AUTH_USERNAME: ${PACT_BROKER_USERNAME}
      PACT_BROKER_BASIC_AUTH_PASSWORD: ${PACT_BROKER_PASSWORD}